# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b5690d77b0b8ff407a14b09e4c967c04656acd2cb3a6f99c713388de637e7992c34ea71348e7efd71ee9d9f552665843182bc38829db4bc63a59368e81fb8e2

test:
  secret_key_base: 70f122fdd4b80fa7cf84e73e907d4c692bd9dc89a2f1c44f8d6a25ed1ae3bc7d6b8c36ac6fbf51a8453397ad5053f4b7d88438d06141e301cd7cc2a6b1bd32e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
